require("mlohier.core.options")
require("mlohier.core.keymaps")
require("mlohier.core.colorscheme")
require("mlohier.plugins-setup")
require("mlohier.plugins.comment")
-- lspsaga should be imported be for lspconfig
require("mlohier.plugins.lsp.lspsaga")
require("mlohier.plugins.lsp.lspconfig")
require("mlohier.plugins.lsp.mason")
require("mlohier.plugins.lualine")
require("mlohier.plugins.nvim-cmp")
require("mlohier.plugins.nvim-tree")
require("mlohier.plugins.telescope")
