require("mlohier.core.options")
require("mlohier.core.keymaps")
require("mlohier.core.colorscheme")
require("mlohier.plugins-setup")
require("mlohier.plugins.comment")
require("mlohier.plugins.nvim-tree")
